#+BEGIN_COMMENT
.. title: Am I back?
.. slug: am-i-back
.. date: 2023-06-17 17:30:44 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Am I back?

I am back to blogging after a long time. I have been busy with my work and a long time dissimilarity of leaving the world of linux to find other systems that the world. So I started to learn System Design in order to facilitate myself with all the other ways. I want to revive this blog as I no longer wonder about math support to be added.

** How to revive this blog?

Admittedly, it was a big of discovery to find out how this blog actually worked. But to make sure that I can have it up and running again. Here is a bit of heads up on how to achieve that quick.

*** Step 1: The Repository

The repository is set up in ~blank-manash/blog~. To start, simply clone it to your system. It contains 2 branches, ~src~ and ~main~, the src is where we would be actively working on, and the ~main~ is from where the pages are published. Make sure you are checked out to the ~src~ branch when you are working on this.

*** Step 2: Nikola

Install Nikola. The offical website asks you to install it using a venv. But the direct install through homebrew on my macbook works fine as well. Everything is already set up, you would want to run these commands.

#+BEGIN_SRC bash
  pip3 install nikola ghp-import
#+END_SRC

*** Step 3: Edit

Now you can simply get started by creating a new page from ~nikola new_post -e~, ~nikola build~, ~nikola serve -b~ and ~nikola github_deploy~. It's self explanatory of what these things mean, but it really is that easy to get started with it.
